# Makefile for the himax touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_HIMAX_HX83112A_NOFLASH) += touchpanel_common_driver.o touchpanel_prevention.o touchpanel_healthinfo.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_HX83112A_NOFLASH) += touch_interfaces.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_HX83112A_NOFLASH) += hx83112a_noflash.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_HX83112A_NOFLASH) += himax_common.o	